/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.lucene.sandbox.codecs.pq;

import static org.apache.lucene.codecs.lucene99.Lucene99HnswVectorsFormat.DEFAULT_BEAM_WIDTH;
import static org.apache.lucene.codecs.lucene99.Lucene99HnswVectorsFormat.DEFAULT_MAX_CONN;
import static org.apache.lucene.codecs.lucene99.Lucene99HnswVectorsFormat.DEFAULT_NUM_MERGE_WORKER;
import static org.apache.lucene.codecs.lucene99.Lucene99HnswVectorsFormat.HNSW_GRAPH_THRESHOLD;
import static org.apache.lucene.codecs.lucene99.Lucene99HnswVectorsFormat.MAXIMUM_BEAM_WIDTH;
import static org.apache.lucene.codecs.lucene99.Lucene99HnswVectorsFormat.MAXIMUM_MAX_CONN;

import java.io.IOException;
import java.util.concurrent.ExecutorService;
import org.apache.lucene.codecs.KnnVectorsFormat;
import org.apache.lucene.codecs.KnnVectorsReader;
import org.apache.lucene.codecs.KnnVectorsWriter;
import org.apache.lucene.codecs.lucene99.Lucene99HnswVectorsReader;
import org.apache.lucene.codecs.lucene99.Lucene99HnswVectorsWriter;
import org.apache.lucene.index.SegmentReadState;
import org.apache.lucene.index.SegmentWriteState;
import org.apache.lucene.search.TaskExecutor;
import org.apache.lucene.store.DataAccessHint;
import org.apache.lucene.store.FileDataHint;
import org.apache.lucene.store.FileTypeHint;

/**
 * An HNSW vectors format whose graph is built on full-precision distances and searched with
 * product-quantized distances, see {@link PQVectorsFormat}.
 *
 * <p>Only FLOAT32 vectors with EUCLIDEAN similarity are supported.
 *
 * @lucene.experimental
 */
public class HnswPQVectorsFormat extends KnnVectorsFormat {

  public static final String NAME = "HnswPQVectorsFormat";

  private final int maxConn;
  private final int beamWidth;
  private final PQVectorsFormat flatVectorsFormat;
  private final int tinySegmentsThreshold;
  private final int numMergeWorkers;
  private final TaskExecutor mergeExec;

  /** Constructs a format using default PQ and graph construction parameters. */
  public HnswPQVectorsFormat() {
    this(PQVectorsFormat.DEFAULT_DIMENSIONS_PER_SUBSPACE, DEFAULT_MAX_CONN, DEFAULT_BEAM_WIDTH);
  }

  /**
   * Constructs a format using the given PQ and graph construction parameters.
   *
   * @param dimensionsPerSubspace dimensions covered by each one-byte code, see {@link
   *     PQVectorsFormat#PQVectorsFormat(int, int, int)}
   * @param maxConn the maximum number of connections to a node in the HNSW graph
   * @param beamWidth the size of the queue maintained during graph construction
   */
  public HnswPQVectorsFormat(int dimensionsPerSubspace, int maxConn, int beamWidth) {
    this(
        new PQVectorsFormat(
            dimensionsPerSubspace,
            PQVectorsFormat.DEFAULT_SAMPLE_SIZE,
            PQVectorsFormat.DEFAULT_TRAINING_ITERATIONS),
        maxConn,
        beamWidth,
        DEFAULT_NUM_MERGE_WORKER,
        null,
        HNSW_GRAPH_THRESHOLD);
  }

  /**
   * Constructs a format using the given PQ and graph construction parameters.
   *
   * @param flatVectorsFormat the product quantization parameters
   * @param maxConn the maximum number of connections to a node in the HNSW graph
   * @param beamWidth the size of the queue maintained during graph construction
   * @param numMergeWorkers number of workers (threads) that will be used when doing merge. If
   *     larger than 1, a non-null {@link ExecutorService} must be passed as mergeExec
   * @param mergeExec the {@link ExecutorService} that will be used by ALL vector writers that are
   *     generated by this format to do the merge
   * @param tinySegmentsThreshold the minimum expected number of visited nodes before a graph is
   *     built, see {@link org.apache.lucene.codecs.lucene99.Lucene99HnswVectorsFormat}
   */
  public HnswPQVectorsFormat(
      PQVectorsFormat flatVectorsFormat,
      int maxConn,
      int beamWidth,
      int numMergeWorkers,
      ExecutorService mergeExec,
      int tinySegmentsThreshold) {
    super(NAME);
    if (maxConn <= 0 || maxConn > MAXIMUM_MAX_CONN) {
      throw new IllegalArgumentException(
          "maxConn must be positive and less than or equal to "
              + MAXIMUM_MAX_CONN
              + "; maxConn="
              + maxConn);
    }
    if (beamWidth <= 0 || beamWidth > MAXIMUM_BEAM_WIDTH) {
      throw new IllegalArgumentException(
          "beamWidth must be positive and less than or equal to "
              + MAXIMUM_BEAM_WIDTH
              + "; beamWidth="
              + beamWidth);
    }
    if (numMergeWorkers == 1 && mergeExec != null) {
      throw new IllegalArgumentException(
          "No executor service is needed as we'll use single thread to merge");
    }
    this.flatVectorsFormat = flatVectorsFormat;
    this.maxConn = maxConn;
    this.beamWidth = beamWidth;
    this.numMergeWorkers = numMergeWorkers;
    this.mergeExec = mergeExec == null ? null : new TaskExecutor(mergeExec);
    this.tinySegmentsThreshold = tinySegmentsThreshold;
  }

  @Override
  public KnnVectorsWriter fieldsWriter(SegmentWriteState state) throws IOException {
    return new Lucene99HnswVectorsWriter(
        state,
        maxConn,
        beamWidth,
        flatVectorsFormat,
        flatVectorsFormat.fieldsWriter(state),
        numMergeWorkers,
        mergeExec,
        tinySegmentsThreshold);
  }

  @Override
  public KnnVectorsReader fieldsReader(SegmentReadState state) throws IOException {
    return new Lucene99HnswVectorsReader(
        state,
        flatVectorsFormat.fieldsReader(
            state.withHints(FileTypeHint.DATA, FileDataHint.KNN_VECTORS, DataAccessHint.RANDOM)));
  }

  @Override
  public int getMaxDimensions(String fieldName) {
    return 1024;
  }

  @Override
  public String toString() {
    return NAME
        + "(maxConn="
        + maxConn
        + ", beamWidth="
        + beamWidth
        + ", tinySegmentsThreshold="
        + tinySegmentsThreshold
        + ", flatVectorFormat="
        + flatVectorsFormat
        + ")";
  }
}
